apiVersion: v1
kind: Pod
metadata:
  name: pvspec-zahi
spec:
  volumes:
    - name: pvspec-vol-zahi
      persistentVolumeClaim:
        claimName: pv1-claim
  containers:
    - name: use-pv
      image: nginx
      ports:
        - containerPort: 80
          name: "http-server"
      volumeMounts:
        - mountPath: "/data"
          name: pvspec-vol-zahi

