---
apiVersion: v1
kind: Namespace
metadata:
  name: finance-zahi
---
apiVersion: v1
kind: Pod
metadata:
  name: temp-bus
  namespace: finance-zahi
spec:
  containers:
  - name: temp-bus
    image: redis:alpine