apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
     run: use-pv
  name: use-pvspec-zahi
spec:
  volumes:
    - name: pvspec-vol-zahi
      persistentVolumeClaim:
        claimName: pv1-claim
  containers:
    - name: use-pv
      image: nginx
      resources: {}
      volumeMounts:
        - mountPath: "/data"
          name: pvspec-vol-zahi
status: {}


