apiVersion: apps/v1
kind: Deployment
metadata:
 name: nginx-deploy
 labels:
  app: nginx
spec:
 template:
   metadata:
     name: nginx-pod
     labels:
       app: nginx
       type: front-end
   spec:
    containers:
    - name: nginx-deploy
      image: nginx:1.16
 replicas: 1
 selector:
  matchLabels:
    type: front-end