kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-analytics
  labels:
    type: local
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/pv/data-analytics"