apiVersion: v1
kind: Pod
metadata:
  name: redis-storage-zahi
spec:
  containers:
  - name: redis-storage-zahi
    image: redis:alpine
    volumeMounts:
    - name: redis-storage-zahi
      mountPath: /data/redis
  volumes:
  - name: redis-storage-zahi
    emptyDir: {}